services:
  nginx:
    build: 
      context: ./infra/nginx
      dockerfile: Dockerfile.local
    container_name: rc-nginx-local
    ports:
      - "8080:80"   
    volumes:
      - ./web-review-center:/srv/app
      - ./infra/nginx/default.local.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - php

  php:
    build: 
      context: ./infra/php
    container_name: rc-php-local
    ports:
      - "9000:9000"   
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./web-review-center:/srv/app
    command: php-fpm

  mysql:
    build:
      context: ./infra/mysql
    container_name: rc-db-local
    ports:
      - "3307:3306"   
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PowerDev_local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    volumes:
      - mysql-volume:/var/lib/mysql

  queue-worker:
    build: 
      context: ./infra/php
    container_name: rc-queue-local
    command: >
      php artisan queue:work database
      --queue=default
      --sleep=1
      --timeout=120
      --tries=3
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./web-review-center:/srv/app
    depends_on:
      - mysql
    working_dir: /srv/app

volumes:
  mysql-volume:
    driver: local 